
package nl.textkernel.home.sourcebox.soap.documentprocessor;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "ProcessDocumentException", targetNamespace = "http://home.textkernel.nl/sourcebox/soap/documentProcessor")
public class ProcessDocumentException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ProcessDocumentException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public ProcessDocumentException_Exception(String message, ProcessDocumentException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public ProcessDocumentException_Exception(String message, ProcessDocumentException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: nl.textkernel.home.sourcebox.soap.documentprocessor.ProcessDocumentException
     */
    public ProcessDocumentException getFaultInfo() {
        return faultInfo;
    }

}
