
package parsing.generateddocumentprocessor;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ProcessDocumentImplService", targetNamespace = "http://home.textkernel.nl/sourcebox/soap/documentProcessor", wsdlLocation = "https://home.textkernel.nl/sourcebox/soap/processDocument?wsdl")
public class ProcessDocumentImplService
    extends Service
{

    private final static URL PROCESSDOCUMENTIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException PROCESSDOCUMENTIMPLSERVICE_EXCEPTION;
    private final static QName PROCESSDOCUMENTIMPLSERVICE_QNAME = new QName("http://home.textkernel.nl/sourcebox/soap/documentProcessor", "ProcessDocumentImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://home.textkernel.nl/sourcebox/soap/processDocument?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PROCESSDOCUMENTIMPLSERVICE_WSDL_LOCATION = url;
        PROCESSDOCUMENTIMPLSERVICE_EXCEPTION = e;
    }

    public ProcessDocumentImplService() {
        super(__getWsdlLocation(), PROCESSDOCUMENTIMPLSERVICE_QNAME);
    }

    public ProcessDocumentImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PROCESSDOCUMENTIMPLSERVICE_QNAME, features);
    }

    public ProcessDocumentImplService(URL wsdlLocation) {
        super(wsdlLocation, PROCESSDOCUMENTIMPLSERVICE_QNAME);
    }

    public ProcessDocumentImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PROCESSDOCUMENTIMPLSERVICE_QNAME, features);
    }

    public ProcessDocumentImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProcessDocumentImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ProcessDocumentInterface
     */
    @WebEndpoint(name = "ProcessDocumentImplPort")
    public ProcessDocumentInterface getProcessDocumentImplPort() {
        return super.getPort(new QName("http://home.textkernel.nl/sourcebox/soap/documentProcessor", "ProcessDocumentImplPort"), ProcessDocumentInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProcessDocumentInterface
     */
    @WebEndpoint(name = "ProcessDocumentImplPort")
    public ProcessDocumentInterface getProcessDocumentImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://home.textkernel.nl/sourcebox/soap/documentProcessor", "ProcessDocumentImplPort"), ProcessDocumentInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PROCESSDOCUMENTIMPLSERVICE_EXCEPTION!= null) {
            throw PROCESSDOCUMENTIMPLSERVICE_EXCEPTION;
        }
        return PROCESSDOCUMENTIMPLSERVICE_WSDL_LOCATION;
    }

}
