
package parsing.generateddocumentprocessor;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ProcessDocumentInterface", targetNamespace = "http://home.textkernel.nl/sourcebox/soap/documentProcessor")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ProcessDocumentInterface {


    /**
     * 
     * @param password
     * @param fileName
     * @param apimap
     * @param options
     * @param account
     * @param fileContent
     * @param tmfFileContent
     * @param username
     * @return
     *     returns java.lang.String
     * @throws ProcessDocumentException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "processDocument", targetNamespace = "http://home.textkernel.nl/sourcebox/soap/documentProcessor", className = "parsing.generateddocumentprocessor.ProcessDocument")
    @ResponseWrapper(localName = "processDocumentResponse", targetNamespace = "http://home.textkernel.nl/sourcebox/soap/documentProcessor", className = "parsing.generateddocumentprocessor.ProcessDocumentResponse")
    @Action(input = "http://home.textkernel.nl/sourcebox/soap/documentProcessor/ProcessDocumentInterface/processDocumentRequest", output = "http://home.textkernel.nl/sourcebox/soap/documentProcessor/ProcessDocumentInterface/processDocumentResponse", fault = {
        @FaultAction(className = ProcessDocumentException_Exception.class, value = "http://home.textkernel.nl/sourcebox/soap/documentProcessor/ProcessDocumentInterface/processDocument/Fault/ProcessDocumentException")
    })
    public String processDocument(
        @WebParam(name = "account", targetNamespace = "")
        String account,
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "password", targetNamespace = "")
        String password,
        @WebParam(name = "fileName", targetNamespace = "")
        String fileName,
        @WebParam(name = "fileContent", targetNamespace = "")
        byte[] fileContent,
        @WebParam(name = "tmfFileContent", targetNamespace = "")
        byte[] tmfFileContent,
        @WebParam(name = "apimap", targetNamespace = "")
        byte[] apimap,
        @WebParam(name = "options", targetNamespace = "")
        List<Entry> options)
        throws ProcessDocumentException_Exception
    ;

    /**
     * 
     * @param password
     * @param fileName
     * @param apimap
     * @param clientSpecificArguments
     * @param options
     * @param account
     * @param fileContent
     * @param tmfFileContent
     * @param username
     * @return
     *     returns java.lang.String
     * @throws ProcessDocumentException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "processDocumentAdvanced", targetNamespace = "http://home.textkernel.nl/sourcebox/soap/documentProcessor", className = "parsing.generateddocumentprocessor.ProcessDocumentAdvanced")
    @ResponseWrapper(localName = "processDocumentAdvancedResponse", targetNamespace = "http://home.textkernel.nl/sourcebox/soap/documentProcessor", className = "parsing.generateddocumentprocessor.ProcessDocumentAdvancedResponse")
    @Action(input = "http://home.textkernel.nl/sourcebox/soap/documentProcessor/ProcessDocumentInterface/processDocumentAdvancedRequest", output = "http://home.textkernel.nl/sourcebox/soap/documentProcessor/ProcessDocumentInterface/processDocumentAdvancedResponse", fault = {
        @FaultAction(className = ProcessDocumentException_Exception.class, value = "http://home.textkernel.nl/sourcebox/soap/documentProcessor/ProcessDocumentInterface/processDocumentAdvanced/Fault/ProcessDocumentException")
    })
    public String processDocumentAdvanced(
        @WebParam(name = "account", targetNamespace = "")
        String account,
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "password", targetNamespace = "")
        String password,
        @WebParam(name = "clientSpecificArguments", targetNamespace = "")
        List<Entry> clientSpecificArguments,
        @WebParam(name = "fileName", targetNamespace = "")
        String fileName,
        @WebParam(name = "fileContent", targetNamespace = "")
        byte[] fileContent,
        @WebParam(name = "tmfFileContent", targetNamespace = "")
        byte[] tmfFileContent,
        @WebParam(name = "apimap", targetNamespace = "")
        byte[] apimap,
        @WebParam(name = "options", targetNamespace = "")
        List<Entry> options)
        throws ProcessDocumentException_Exception
    ;

    /**
     * 
     * @param password
     * @param customQueryString
     * @param publicURL
     * @param options
     * @param outputType
     * @param account
     * @param username
     * @return
     *     returns byte[]
     * @throws ProcessDocumentException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "processURLAtomic", targetNamespace = "http://home.textkernel.nl/sourcebox/soap/documentProcessor", className = "parsing.generateddocumentprocessor.ProcessURLAtomic")
    @ResponseWrapper(localName = "processURLAtomicResponse", targetNamespace = "http://home.textkernel.nl/sourcebox/soap/documentProcessor", className = "parsing.generateddocumentprocessor.ProcessURLAtomicResponse")
    @Action(input = "http://home.textkernel.nl/sourcebox/soap/documentProcessor/ProcessDocumentInterface/processURLAtomicRequest", output = "http://home.textkernel.nl/sourcebox/soap/documentProcessor/ProcessDocumentInterface/processURLAtomicResponse", fault = {
        @FaultAction(className = ProcessDocumentException_Exception.class, value = "http://home.textkernel.nl/sourcebox/soap/documentProcessor/ProcessDocumentInterface/processURLAtomic/Fault/ProcessDocumentException")
    })
    public byte[] processURLAtomic(
        @WebParam(name = "account", targetNamespace = "")
        String account,
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "password", targetNamespace = "")
        String password,
        @WebParam(name = "publicURL", targetNamespace = "")
        String publicURL,
        @WebParam(name = "outputType", targetNamespace = "")
        String outputType,
        @WebParam(name = "customQueryString", targetNamespace = "")
        String customQueryString,
        @WebParam(name = "options", targetNamespace = "")
        List<Entry> options)
        throws ProcessDocumentException_Exception
    ;

}
